/**
 * ข้อมูลตัวอย่างสำหรับ MVP dashboard — ของจริงจะมาจาก Google Sheet `referrals`
 * โครงสร้างอ้างอิง src/lib/referral-types.ts
 */

import type { Referral } from "./referral-types";
import type { FellowClinicDay } from "./fellow-schedule";

export const MOCK_REFERRALS: Referral[] = [
  /* ---------- กลุ่มที่ 1: Transplant appointment ---------- */
  {
    referralId: "HEM-20260727-0001",
    referralType: "TRANSPLANT_APPOINTMENT",
    diseaseGroup: "Acute Leukemia",
    submittedAt: "2026-07-27 09:12",
    referrerOrg: "โรงพยาบาลสมุทรสาคร",
    referrerName: "",
    referrerPhone: "081-234-5678",
    insuranceScheme: "บัตรทอง",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Urgent",
    status: "Incomplete",
    assignedTo: "พญ. สุดา (Fellow transplant)",
    elapsedBusinessHours: 50,
    followUpDate: "2026-07-30",
    possibleDuplicateOf: null,
    appointmentDate: null,
    fellowAssigned: null,
    note: "ขาดผล Chromosome และ Molecular mutation — แจ้งขอเอกสารเพิ่มแล้ว",
    diagnosis: "",
    stage: "",
    treatmentSummary: "",
    comorbidity: "",
    clinicalQuestion: "",
    adviceRecord: "",
    transplantIndication: "",
  },
  {
    referralId: "HEM-20260728-0002",
    referralType: "TRANSPLANT_APPOINTMENT",
    diseaseGroup: "Multiple Myeloma",
    submittedAt: "2026-07-28 11:40",
    referrerOrg: "โรงพยาบาลราชบุรี",
    referrerName: "",
    referrerPhone: "089-111-2233",
    insuranceScheme: "ข้าราชการ",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Routine",
    status: "Slot Reserved",
    assignedTo: null, // จองคิวจริงไม่เขียน assigned_to — ทดสอบ fallback ไป fellowAssigned,
    elapsedBusinessHours: 14,
    followUpDate: "2026-08-05",
    possibleDuplicateOf: null,
    appointmentDate: "2026-08-05",
    fellowAssigned: "พญ. สุดา",
    note: "จองคิววันที่ 5 ส.ค. (คิวที่ 1 จาก 2)",
    diagnosis: "",
    stage: "",
    treatmentSummary: "",
    comorbidity: "",
    clinicalQuestion: "",
    adviceRecord: "",
    transplantIndication: "",
  },
  {
    referralId: "HEM-20260729-0003",
    referralType: "TRANSPLANT_APPOINTMENT",
    diseaseGroup: "Lymphoma",
    submittedAt: "2026-07-29 08:05",
    referrerOrg: "โรงพยาบาลนครปฐม",
    referrerName: "",
    referrerPhone: "086-555-9090",
    insuranceScheme: "ประกันสังคม",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Urgent",
    status: "Pending Review",
    assignedTo: null,
    elapsedBusinessHours: 2,
    followUpDate: "2026-07-30",
    possibleDuplicateOf: null,
    appointmentDate: null,
    fellowAssigned: null,
    note: "รอแอดมินกลางจัดคิว fellow",
    diagnosis: "",
    stage: "",
    treatmentSummary: "",
    comorbidity: "",
    clinicalQuestion: "",
    adviceRecord: "",
    transplantIndication: "",
  },
  {
    referralId: "HEM-20260722-0004",
    referralType: "TRANSPLANT_APPOINTMENT",
    diseaseGroup: "Acute Leukemia",
    submittedAt: "2026-07-22 14:20",
    referrerOrg: "โรงพยาบาลสมเด็จพระพุทธเลิศหล้า",
    referrerName: "",
    referrerPhone: "092-777-1414",
    insuranceScheme: "ชำระเงินเอง",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Urgent",
    status: "Appointment Confirmed",
    assignedTo: "พญ. สุดา (Fellow transplant)",
    elapsedBusinessHours: 20,
    followUpDate: "2026-08-03",
    possibleDuplicateOf: null,
    appointmentDate: "2026-08-03",
    fellowAssigned: "พญ. สุดา",
    note: "นัด 3 ส.ค. 08:00 น. ที่ OPD 700 — พี่น้องมาตรวจ HLA ด้วย",
    diagnosis: "",
    stage: "",
    treatmentSummary: "",
    comorbidity: "",
    clinicalQuestion: "",
    adviceRecord: "",
    transplantIndication: "",
  },
  {
    referralId: "HEM-20260730-0015",
    referralType: "TRANSPLANT_APPOINTMENT",
    diseaseGroup: "MDS",
    submittedAt: "2026-07-30 09:15",
    referrerOrg: "โรงพยาบาลสุราษฎร์ธานี",
    referrerName: "",
    referrerPhone: "081-447-2200",
    insuranceScheme: "บัตรทอง",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Urgent",
    status: "Pending Review",
    assignedTo: null,
    elapsedBusinessHours: 6,
    followUpDate: "2026-08-03",
    possibleDuplicateOf: null,
    appointmentDate: null,
    fellowAssigned: null,
    note: "High-risk MDS (IPSS-R 5.5) — พิจารณา allogeneic SCT",
    diagnosis: "",
    stage: "",
    treatmentSummary: "",
    comorbidity: "",
    clinicalQuestion: "",
    adviceRecord: "",
    transplantIndication: "",
  },

  /* ---------- กลุ่มที่ 2: Regimen consult ---------- */
  {
    referralId: "HEM-20260728-0005",
    referralType: "REGIMEN_CONSULT",
    diseaseGroup: "Lymphoma",
    submittedAt: "2026-07-28 13:02",
    dentUnread: true,
    referrerOrg: "โรงพยาบาลเพชรบุรี",
    referrerName: "",
    referrerPhone: "084-321-7788",
    insuranceScheme: "ข้าราชการ",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Routine",
    status: "Awaiting Attending",
    assignedTo: "นพ. ปกรณ์ (R3 วอร์ดเคโม)",
    elapsedBusinessHours: 12,
    followUpDate: "2026-07-30",
    possibleDuplicateOf: null,
    appointmentDate: null,
    fellowAssigned: null,
    note: "เลือกสูตร R-CHOP จาก Template Library แล้ว รออาจารย์ตรวจทาน",
    diagnosis: "DLBCL, GCB subtype",
    stage: "Stage IIIA, IPI 2 (intermediate-low)",
    treatmentSummary:
      "ยังไม่ได้เริ่มเคมีบำบัด ได้ CT ทั้งตัวและ bone marrow biopsy แล้ว ไม่มี marrow involvement",
    comorbidity: "DM type 2 คุมได้ด้วยยากิน, eGFR 68",
    clinicalQuestion:
      "เริ่ม R-CHOP ที่ รพ. ต้นทางได้เลยหรือไม่ ต้องปรับขนาดยาตามการทำงานของไตหรือเปล่า และควรให้ G-CSF ป้องกันตั้งแต่ cycle แรกไหม",
    adviceRecord: "",
    transplantIndication: "",
  },
  {
    referralId: "HEM-20260724-0006",
    referralType: "REGIMEN_CONSULT",
    diseaseGroup: "Acute Leukemia",
    submittedAt: "2026-07-24 10:15",
    referrerOrg: "โรงพยาบาลสระบุรี",
    referrerName: "",
    referrerPhone: "081-909-3344",
    insuranceScheme: "ประกันสังคม",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "REGIMEN_CHOICE",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Urgent",
    status: "Advice Sent",
    assignedTo: "พญ. ชนิกา (R2 วอร์ดเคโม)",
    elapsedBusinessHours: 18,
    followUpDate: null,
    possibleDuplicateOf: null,
    appointmentDate: null,
    fellowAssigned: null,
    note: "ส่งคำแนะนำสูตรยาและเบอร์ติดต่อกลับให้แพทย์ต้นทางแล้ว",
    diagnosis: "APL (PML-RARA positive)",
    stage: "Low risk (WBC 2,400, platelet 62,000)",
    treatmentSummary: "เริ่ม ATRA ทันทีที่สงสัย รอผล molecular ยืนยัน",
    comorbidity: "ไม่มี",
    clinicalQuestion:
      "ขอสูตร ATRA + ATO และแนวทางเฝ้าระวัง differentiation syndrome",
    transplantIndication: "",
    adviceRecord:
      "ให้ ATRA 45 mg/m2/day ร่วมกับ ATO 0.15 mg/kg/day ต่อเนื่องจน CR เฝ้าระวัง differentiation syndrome และ QTc ทุกสัปดาห์ หากมีอาการให้ dexamethasone 10 mg IV q12h ทันที",
  },
  {
    referralId: "HEM-20260727-0007",
    referralType: "REGIMEN_CONSULT",
    diseaseGroup: "Other Hematology",
    submittedAt: "2026-07-27 15:48",
    referrerOrg: "โรงพยาบาลอ่างทอง",
    referrerName: "",
    referrerPhone: "087-222-6161",
    insuranceScheme: "ชำระเงินเอง",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Routine",
    status: "Pending Review",
    assignedTo: null,
    elapsedBusinessHours: 26,
    followUpDate: "2026-07-30",
    possibleDuplicateOf: null,
    appointmentDate: null,
    fellowAssigned: null,
    note: "ไม่มีสูตรมาตรฐานตรงเคส — ต้องปรึกษาอาจารย์โดยตรง",
    diagnosis: "Warm autoimmune hemolytic anemia ดื้อต่อสเตียรอยด์",
    stage: "Hb 6.8 g/dL, reticulocyte 12%, DAT IgG+C3d positive",
    treatmentSummary:
      "Prednisolone 1 mg/kg/day นาน 4 สัปดาห์ ไม่ตอบสนอง ให้เลือดไปแล้ว 4 ยูนิตใน 3 สัปดาห์",
    comorbidity: "ไม่มี",
    clinicalQuestion:
      "ขั้นต่อไปควรใช้ rituximab หรือส่งตัดม้าม ถ้าใช้ rituximab ให้ที่ รพ. ต้นทางได้ไหม ต้องเตรียมวัคซีนอะไรก่อน",
    adviceRecord: "",
    transplantIndication: "",
  },
  {
    referralId: "HEM-20260730-0016",
    referralType: "REGIMEN_CONSULT",
    diseaseGroup: "CML",
    submittedAt: "2026-07-30 11:40",
    referrerOrg: "โรงพยาบาลราชบุรี",
    referrerName: "",
    referrerPhone: "089-330-7788",
    insuranceScheme: "บัตรทอง",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ตัวอย่างเคสกลุ่ม 2 ที่ยังไม่ตอบและอีเมลไม่ผ่านการยืนยัน (สองอีเมลที่กรอกไม่ตรงกัน)
    // ใช้ทดสอบธง "⚠️ อีเมลยังไม่ยืนยัน" บน dashboard
    emailUnverified: true,
    urgency: "Routine",
    status: "Awaiting Attending",
    assignedTo: "พญ. ชนิกา (R2 วอร์ดเคโม)",
    elapsedBusinessHours: 4,
    followUpDate: "2026-08-03",
    possibleDuplicateOf: null,
    appointmentDate: null,
    fellowAssigned: null,
    note: "ดื้อ imatinib — ปรึกษาการเปลี่ยน TKI",
    diagnosis: "CML, chronic phase",
    stage: "BCR-ABL1 IS 4.2% ที่ 12 เดือน (ยังไม่ถึง MMR)",
    treatmentSummary:
      "Imatinib 400 mg/day 12 เดือน ผู้ป่วยกินยาสม่ำเสมอ ตรวจ mutation analysis แล้วไม่พบ T315I",
    comorbidity: "ความดันโลหิตสูง, ไขมันในเลือดสูง",
    clinicalQuestion:
      "ควรเพิ่มขนาด imatinib เป็น 600-800 mg หรือเปลี่ยนเป็น 2nd generation TKI ถ้าเปลี่ยนควรใช้ตัวใด เมื่อคำนึงถึงความเสี่ยงหลอดเลือด",
    adviceRecord: "",
    transplantIndication: "",
  },

  /* ---------- กลุ่มที่ 3: Chemo admission ---------- */
  {
    referralId: "HEM-20260723-0008",
    referralType: "CHEMO_ADMISSION",
    diseaseGroup: "Acute Leukemia",
    submittedAt: "2026-07-23 08:55",
    referrerOrg: "โรงพยาบาลสิงห์บุรี",
    referrerName: "",
    referrerPhone: "083-444-5252",
    insuranceScheme: "ข้าราชการ",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Urgent",
    status: "Awaiting Attending",
    assignedTo: "นพ. ปกรณ์ (R3 วอร์ดเคโม)",
    elapsedBusinessHours: 52,
    followUpDate: "2026-07-30",
    possibleDuplicateOf: null,
    appointmentDate: null,
    fellowAssigned: null,
    note: "รออาจารย์ตรวจทานก่อนตอบกลับ — ค้างเกิน 48 ชม.",
    diagnosis: "AML with myelodysplasia-related changes",
    stage: "Blast ในไขกระดูก 38%, karyotype complex",
    treatmentSummary:
      "ยังไม่ได้เริ่มเคมีบำบัด ให้เลือดและเกล็ดเลือดประคับประคองอยู่ ECOG 1",
    comorbidity: "COPD, EF 55%",
    clinicalQuestion:
      "ขอส่งตัวมารับ induction 7+3 ที่ศิริราช เนื่องจาก รพ. ต้นทางไม่มีห้องแยกและไม่มีเกล็ดเลือดสำรองเพียงพอ",
    adviceRecord: "",
    transplantIndication: "",
  },
  {
    referralId: "HEM-20260728-0009",
    referralType: "CHEMO_ADMISSION",
    diseaseGroup: "Lymphoma",
    submittedAt: "2026-07-28 09:30",
    referrerOrg: "โรงพยาบาลชัยนาท",
    referrerName: "",
    referrerPhone: "090-808-1212",
    insuranceScheme: "ประกันสังคม",
    appointmentNote: "จันทร์ 15 ก.ย. 2569 เวลา 08:00 น. ที่ OPD 700 (ประเมินความพร้อมก่อนรับไว้ให้ยาเคมีบำบัด)",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Urgent",
    status: "Readiness Visit Scheduled",
    assignedTo: "พญ. ชนิกา (R2 วอร์ดเคโม)",
    elapsedBusinessHours: 16,
    followUpDate: "2026-07-31",
    possibleDuplicateOf: null,
    appointmentDate: "2026-09-15",
    fellowAssigned: null,
    note: "นัดประเมินร่างกายที่ OPD 700 วันที่ 31 ก.ค. — จนท. ทำนัดแล้ว",
    diagnosis: "",
    stage: "",
    treatmentSummary: "",
    comorbidity: "",
    clinicalQuestion: "",
    adviceRecord: "รับไว้ประเมินความพร้อมก่อนให้ยาเคมีบำบัด กรุณาส่งผู้ป่วยมาตามวันนัดพร้อมผล CBC ล่าสุด",
    transplantIndication: "",
  },
  {
    referralId: "HEM-20260729-0010",
    referralType: "CHEMO_ADMISSION",
    diseaseGroup: "Multiple Myeloma",
    submittedAt: "2026-07-29 07:45",
    referrerOrg: "โรงพยาบาลกาญจนบุรี",
    referrerName: "",
    referrerPhone: "085-676-8899",
    insuranceScheme: "ชำระเงินเอง",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Routine",
    status: "Submitted",
    assignedTo: null,
    elapsedBusinessHours: 3,
    followUpDate: null,
    possibleDuplicateOf: "HEM-20260728-0002",
    appointmentDate: null,
    fellowAssigned: null,
    note: "ระบบพบชื่อ-นามสกุลใกล้เคียงกับเคสกลุ่ม 1 ที่ยื่นเมื่อวาน — ให้ตรวจสอบ",
    diagnosis: "Multiple myeloma, IgG kappa",
    stage: "R-ISS II",
    treatmentSummary:
      "VRd ครบ 4 cycles ตอบสนองบางส่วน (VGPR) มีปลายประสาทอักเสบระดับ 2",
    comorbidity: "CKD stage 3, creatinine 1.9",
    clinicalQuestion:
      "ขอส่งตัวมาให้ cycle ถัดไปที่ศิริราช และขอความเห็นเรื่องปรับ bortezomib เป็นสัปดาห์ละครั้งเพราะปลายประสาทอักเสบ",
    adviceRecord: "",
    transplantIndication: "",
  },
  {
    referralId: "HEM-20260721-0011",
    referralType: "CHEMO_ADMISSION",
    diseaseGroup: "Aplastic Anemia / BMF",
    submittedAt: "2026-07-21 14:10",
    referrerOrg: "โรงพยาบาลสุพรรณบุรี",
    referrerName: "",
    referrerPhone: "088-343-7070",
    insuranceScheme: "บัตรทอง",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "ADMISSION",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Routine",
    status: "Advice Sent",
    assignedTo: "นพ. ปกรณ์ (R3 วอร์ดเคโม)",
    elapsedBusinessHours: 22,
    followUpDate: null,
    possibleDuplicateOf: null,
    appointmentDate: null,
    fellowAssigned: null,
    note: "ประเมินแล้วแพทย์ต้นทางดูแลต่อได้เอง — ส่งคำแนะนำกลับพร้อมบันทึกใน record",
    diagnosis: "ITP เรื้อรัง",
    stage: "Platelet 28,000 ไม่มีเลือดออก",
    treatmentSummary: "Prednisolone แล้วค่อยลดขนาด ปัจจุบัน 10 mg/day",
    comorbidity: "ไม่มี",
    clinicalQuestion: "ต้องส่งตัวมารักษาต่อที่ศิริราชหรือไม่",
    transplantIndication: "",
    adviceRecord:
      "ระดับเกล็ดเลือดนี้ยังไม่มีข้อบ่งชี้ต้องส่งตัว ดูแลต่อที่ รพ. ต้นทางได้ ติดตาม CBC ทุก 2 สัปดาห์ หากต่ำกว่า 20,000 หรือมีเลือดออกจึงส่งปรึกษาอีกครั้ง",
  },

  /* ---------- กลุ่มที่ 4: General OPD (fully automated) ---------- */
  {
    referralId: "HEM-20260729-0012",
    referralType: "GENERAL_OPD",
    diseaseGroup: null,
    submittedAt: "2026-07-29 08:20",
    referrerOrg: "โรงพยาบาลนครนายก",
    referrerName: "",
    referrerPhone: "081-565-2323",
    insuranceScheme: "ข้าราชการ",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Routine",
    status: "Auto Replied",
    assignedTo: null,
    elapsedBusinessHours: 2,
    followUpDate: null,
    possibleDuplicateOf: null,
    appointmentDate: null,
    fellowAssigned: null,
    note: "ระบบส่ง QR code นัดหมายกลางให้ผู้ป่วยอัตโนมัติ",
    diagnosis: "",
    stage: "",
    treatmentSummary: "",
    comorbidity: "",
    clinicalQuestion: "",
    adviceRecord: "",
    transplantIndication: "",
  },
  {
    referralId: "HEM-20260728-0013",
    referralType: "GENERAL_OPD",
    diseaseGroup: null,
    submittedAt: "2026-07-28 16:05",
    referrerOrg: "โรงพยาบาลปทุมธานี",
    referrerName: "",
    referrerPhone: "082-119-4545",
    insuranceScheme: "ประกันสังคม",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Routine",
    status: "Auto Replied",
    assignedTo: null,
    elapsedBusinessHours: 9,
    followUpDate: null,
    possibleDuplicateOf: null,
    appointmentDate: null,
    fellowAssigned: null,
    note: "",
    diagnosis: "",
    stage: "",
    treatmentSummary: "",
    comorbidity: "",
    clinicalQuestion: "",
    adviceRecord: "",
    transplantIndication: "",
  },
  {
    referralId: "HEM-20260726-0014",
    referralType: "GENERAL_OPD",
    diseaseGroup: null,
    submittedAt: "2026-07-26 10:32",
    referrerOrg: "โรงพยาบาลลพบุรี",
    referrerName: "",
    referrerPhone: "089-654-3210",
    insuranceScheme: "ชำระเงินเอง",
    appointmentNote: "",
    adviceRegimens: "",
    questionType: "",
    answeredBy: "",
    adviceAttending: "",
    // ข้อมูลตัวอย่างส่วนใหญ่ไม่มีปัญหาเรื่องอีเมล — ดูข้อยกเว้นที่ HEM-20260730-0016
    emailUnverified: false,
    urgency: "Routine",
    status: "Closed",
    assignedTo: null,
    elapsedBusinessHours: 6,
    followUpDate: null,
    possibleDuplicateOf: null,
    appointmentDate: null,
    fellowAssigned: null,
    note: "ผู้ป่วยได้รับใบนัดจากระบบนัดหมายกลางแล้ว",
    diagnosis: "",
    stage: "",
    treatmentSummary: "",
    comorbidity: "",
    clinicalQuestion: "",
    adviceRecord: "",
    transplantIndication: "",
  },
];

/**
 * ตารางออกตรวจ fellow ตัวอย่าง — ใช้เฉพาะตอนยังไม่ได้ต่อ Google Sheet
 * ของจริงมาจากชีต `fellow_schedule` ที่แพทย์แอดมินกรอกเอง
 */
export const MOCK_FELLOW_SCHEDULE: FellowClinicDay[] = [
  { clinicDate: "2026-08-03", fellowName: "พญ. สุดา", maxSlots: 2, note: "" },
  { clinicDate: "2026-08-05", fellowName: "พญ. สุดา", maxSlots: 2, note: "" },
  { clinicDate: "2026-08-05", fellowName: "นพ. ธนกร", maxSlots: 2, note: "" },
  { clinicDate: "2026-08-12", fellowName: "นพ. ธนกร", maxSlots: 2, note: "" },
  {
    clinicDate: "2026-08-17",
    fellowName: "พญ. สุดา",
    maxSlots: 1,
    note: "ครึ่งวันเช้า",
  },
  { clinicDate: "2026-08-19", fellowName: "นพ. ธนกร", maxSlots: 2, note: "" },
  { clinicDate: "2026-08-26", fellowName: "พญ. สุดา", maxSlots: 2, note: "" },
  { clinicDate: "2026-09-02", fellowName: "นพ. ธนกร", maxSlots: 2, note: "" },
  { clinicDate: "2026-09-09", fellowName: "พญ. สุดา", maxSlots: 2, note: "" },
].map((day, index) => ({
  ...day,
  startTime: "09:00",
  endTime: "12:00",
  rowNumber: index + 2,
}));
